"""21.06.1906

Revision ID: 2785e70fb724
Revises: c7e8a043a7ee
Create Date: 2025-06-21 19:06:16.970055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2785e70fb724'
down_revision: Union[str, Sequence[str], None] = 'c7e8a043a7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE activitys SET description = 'An activity description' WHERE description IS NULL")
    op.alter_column('activitys', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False, server_default='An activity description')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activitys', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
