"""Third commit

Revision ID: 28b38287677f
Revises: f9970ac82521
Create Date: 2025-06-19 17:09:40.610052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28b38287677f'
down_revision: Union[str, Sequence[str], None] = 'f9970ac82521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'offline')
    op.drop_column('employees', 'date_of_creation')
    op.drop_column('employees', 'date_of_update')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('date_of_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('date_of_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('offline', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
