"""New schema changes

Revision ID: 391f42549bcc
Revises: 220a99709ae0
Create Date: 2025-07-16 12:19:06.117015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391f42549bcc'
down_revision: Union[str, Sequence[str], None] = '220a99709ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_activity',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activitys.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'activity_id')
    )
    op.add_column('employees', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('employees_activity_now_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['id'])
    op.drop_column('employees', 'role')
    op.drop_column('employees', 'activity_now')
    op.add_column('servers', sa.Column('password', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('server_key', sa.String(), nullable=True))
    op.drop_column('servers', 'ip')
    op.drop_column('servers', 'port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('port', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('servers', sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('servers', 'server_key')
    op.drop_column('servers', 'password')
    op.add_column('employees', sa.Column('activity_now', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_activity_now_fkey'), 'employees', 'activitys', ['activity_now'], ['id'])
    op.drop_column('employees', 'role_id')
    op.drop_table('role_activity')
    op.drop_table('roles')
    # ### end Alembic commands ###
