"""add servers 3

Revision ID: 4ffb2df6786f
Revises: 6177623edbf1
Create Date: 2025-06-27 14:30:40.571353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffb2df6786f'
down_revision: Union[str, Sequence[str], None] = '6177623edbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_employee')
    op.add_column('employees', sa.Column('server_id', sa.Integer(), nullable=True))
    op.execute('UPDATE employees SET server_id = 1')
    op.create_foreign_key(None, 'employees', 'servers', ['server_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'server_id')
    op.create_table('server_employee',
    sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('server_employee_employee_id_fkey')),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('server_employee_server_id_fkey')),
    sa.PrimaryKeyConstraint('server_id', 'employee_id', name=op.f('server_employee_pkey'))
    )
    # ### end Alembic commands ###
