"""add new online system

Revision ID: 653de2de3c13
Revises: 2ade52a4267a
Create Date: 2025-07-15 20:53:53.597225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653de2de3c13'
down_revision: Union[str, Sequence[str], None] = '2ade52a4267a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('agent_status', sa.Text(), nullable=True))
    op.drop_column('employees', 'online')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('online', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('employees', 'agent_status')
    # ### end Alembic commands ###
