"""add roles

Revision ID: 7104d3785a93
Revises: f7f0511a2723
Create Date: 2025-07-14 11:59:22.749225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7104d3785a93'
down_revision: Union[str, Sequence[str], None] = 'f7f0511a2723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_activity',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activitys.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'activity_id')
    )
    op.add_column('employees', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'roles', ['role_id'], ['id'])
    op.drop_column('employees', 'role')
    op.add_column('servers', sa.Column('username', sa.String(), nullable=True))
    op.execute("UPDATE servers SET username = 'default_user' WHERE username IS NULL")
    op.alter_column('servers', 'username', nullable=False)
    op.add_column('servers', sa.Column('server_id', sa.String(), nullable=True))
    op.execute("UPDATE servers SET server_id = 'default_server_id' WHERE server_id IS NULL")
    op.alter_column('servers', 'server_id', nullable=False)
    op.add_column('servers', sa.Column('password', sa.Integer(), nullable=True))
    op.execute("UPDATE servers SET password = 0 WHERE password IS NULL")
    op.alter_column('servers', 'password', nullable=False)
    op.drop_column('servers', 'ip')
    op.drop_column('servers', 'port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('port', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('servers', sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('servers', 'password')
    op.drop_column('servers', 'server_id')
    op.drop_column('servers', 'username')
    op.add_column('employees', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'role_id')
    op.drop_table('role_activity')
    op.drop_table('roles')
    # ### end Alembic commands ###
