"""password string

Revision ID: 763c934a1aeb
Revises: 80957ab96f6a
Create Date: 2025-07-14 16:26:11.215231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763c934a1aeb'
down_revision: Union[str, Sequence[str], None] = '80957ab96f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'password',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'password',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###

"""remove_online_from_employees

Revision ID: remove_online_from_employees
Revises: 763c934a1aeb
Create Date: 2024-07-01

"""
from alembic import op
import sqlalchemy as sa

def upgrade():
    op.drop_column('employees', 'online')

def downgrade():
    op.add_column('employees', sa.Column('online', sa.Boolean(), nullable=True))
