"""delete activity now

Revision ID: 80957ab96f6a
Revises: 0f4c096608d6
Create Date: 2025-07-14 12:41:02.875061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80957ab96f6a'
down_revision: Union[str, Sequence[str], None] = '0f4c096608d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_activity_now_fkey'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'activity_now')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('activity_now', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('employees_activity_now_fkey'), 'employees', 'activitys', ['activity_now'], ['id'])
    # ### end Alembic commands ###
