"""new server table

Revision ID: 932c757fbfbc
Revises: 763c934a1aeb
Create Date: 2025-07-14 16:42:01.521691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932c757fbfbc'
down_revision: Union[str, Sequence[str], None] = '763c934a1aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('server_key', sa.String(), nullable=True))
    op.execute("UPDATE servers SET server_key = 'some_value' WHERE server_key IS NULL")
    op.alter_column('servers', 'server_key', nullable=False, server_default=None)
    op.drop_column('servers', 'server_id')
    op.drop_column('servers', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('servers', sa.Column('server_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('servers', 'server_key')
    # ### end Alembic commands ###
