"""url nullable

Revision ID: a94bc28ff29d
Revises: 4ffb2df6786f
Create Date: 2025-07-08 23:07:58.844121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94bc28ff29d'
down_revision: Union[str, Sequence[str], None] = '4ffb2df6786f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activitys', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activitys', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
