"""add activity_rate to employee

Revision ID: b0366bdd6789
Revises: 909bc4a4286d
Create Date: 2025-06-24 16:33:04.053916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0366bdd6789'
down_revision: Union[str, Sequence[str], None] = '909bc4a4286d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('activity_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'activity_rate')
    # ### end Alembic commands ###
