"""os added

Revision ID: c68311263b6c
Revises: 7fc70be643ff
Create Date: 2025-06-20 16:05:15.477819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68311263b6c'
down_revision: Union[str, Sequence[str], None] = '7fc70be643ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitys', sa.Column('os', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitys', 'os')
    # ### end Alembic commands ###
