"""employees added

Revision ID: e1710c05b07e
Revises: c68311263b6c
Create Date: 2025-06-20 16:11:42.659159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1710c05b07e'
down_revision: Union[str, Sequence[str], None] = 'c68311263b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activitys', 'os',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('employees', sa.Column('activity_now', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('activities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activitys', 'os',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('employees', 'activity_now')
    op.drop_column('employees', 'activities')
    # ### end Alembic commands ###
