"""delete surname

Revision ID: f7f0511a2723
Revises: ccd05c9e0d16
Create Date: 2025-07-09 11:30:20.200425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f0511a2723'
down_revision: Union[str, Sequence[str], None] = 'ccd05c9e0d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
