"""Second commit

Revision ID: f9970ac82521
Revises: 4100c5456ca7
Create Date: 2025-06-19 16:48:48.327515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9970ac82521'
down_revision: Union[str, Sequence[str], None] = '4100c5456ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('offline', sa.Boolean(), nullable=False))
    op.add_column('employees', sa.Column('activity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employees', 'activitys', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'activity_id')
    op.drop_column('employees', 'offline')
    # ### end Alembic commands ###
