# Generated by Django 5.2.3 on 2025-06-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servers',
            new_name='Server',
        ),
    ]
